language: javascript

services:
    - docker

before_install:
  - yarn install
  - yarn build
  - docker build -t bradleylandis/hangman-react .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
