language: node_js
node_js:
  - "10"

services:
  - docker

before_install:
  - npm install
  - npm run build
  - docker build -t bradleylandis/hangman-react .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker push bradleylandis/hangman-react
