# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'webserver-image:$(build.buildId)'

steps:
- script: yarn install
  displayName: 'yarn install'
- script: yarn build
  displayName: 'yarn build'
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: 'bradleylandis.azurecr.io/repositoryname:$(Build.BuildId)'
- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: 'bradleylandis'
    azureContainerRegistry: bradleylandis.azurecr.io
    command: login
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: 'bradleylandis.azurecr.io/$repositoryname:$(Build.BuildId)'
